root: true
env:
  browser: true
  es2021: true
extends:
  - google
  - eslint-config-prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {}
settings:
  import/resolver:
    alias:
      map:
        - ['@', './src']
        - ['~', './node_modules']
      extensions:
        - .js
